# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 15
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - uses: SwiftyLab/setup-swift@latest
    - name: Build
      run: xcodebuild -scheme "SwiftUIRouter" -destination 'platform=iOS Simulator,name=iPhone 16' -UseModernBuildSystem=YES clean build
