# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_16.2.app
        
    - name: Clean Package Cache
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        rm -rf ~/Library/Caches/org.swift.swiftpm/
        
    - name: Resolve Dependencies
      run: |
        xcodebuild -resolvePackageDependencies \
          -scheme "SwiftUIRouter" \
          -scmProvider system
        
    - name: Build
      run: |
        xcodebuild \
          -scheme "SwiftUIRouter" \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -parallelizeTargets \
          -quiet \
          clean build
          
    - name: Test
      run: |
        xcodebuild test \
          -scheme "SwiftUIRouter" \
          -destination 'platform=iOS Simulator,name=iPhone 16'
